stages:
  - build

variables:
  BUILD_DIR: build

before_script:
  - git submodule update --init --recursive

build_linux_x86:
  stage: build
  image: gcc:latest
  script:
    - mkdir -p $BUILD_DIR
    - gcc -Wall -O0 client.c -lm -o $BUILD_DIR/client_linux_x86
  artifacts:
    paths:
      - $BUILD_DIR/client_linux_x86

build_linux_arm:
  stage: build
  image: multiarch/crossbuild
  script:
    - mkdir -p $BUILD_DIR
    - /usr/local/bin/qemu-arm-static gcc -Wall -O0 client.c -lm -o $BUILD_DIR/client_linux_arm
  artifacts:
    paths:
      - $BUILD_DIR/client_linux_arm

build_windows_x86:
  stage: build
  image: gcc:latest
  script:
    - mkdir -p $BUILD_DIR
    - x86_64-w64-mingw32-gcc -Wall -O0 client.c -lm -o $BUILD_DIR/client_windows_x86.exe
  artifacts:
    paths:
      - $BUILD_DIR/client_windows_x86.exe

build_windows_arm:
  stage: build
  image: gcc:latest
  script:
    - mkdir -p $BUILD_DIR
    - arm-none-eabi-gcc -Wall -O0 client.c -lm -o $BUILD_DIR/client_windows_arm.exe
  artifacts:
    paths:
      - $BUILD_DIR/client_windows_arm.exe

build_macos_x86:
  stage: build
  tags:
    - macos
  script:
    - mkdir -p $BUILD_DIR
    - gcc -Wall -O0 client.c -lm -o $BUILD_DIR/client_macos_x86
  artifacts:
    paths:
      - $BUILD_DIR/client_macos_x86

build_macos_arm:
  stage: build
  tags:
    - macos
  script:
    - mkdir -p $BUILD_DIR
    - gcc -Wall -O0 client.c -lm -o $BUILD_DIR/client_macos_arm
  artifacts:
    paths:
      - $BUILD_DIR/client_macos_arm
